<a href="https://colab.research.google.com/github/rutujas11/Machine-Learning-Models/blob/main/Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import drive
%matplotlib inline

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Demo Datasets/balance-scale.data',sep=',')
df.head()

B  1  1.1  1.2  1.3
0  R  1    1    1    2
1  R  1    1    1    3
2  R  1    1    1    4
3  R  1    1    1    5
4  R  1    1    2    1

In [ ]:
df.rename(columns = {'B':'Class Name', '1':'left weight','1.1':'left distance','1.2':'right weight','1.3':'right distance'},inplace = True)


In [ ]:
df.head()

Class Name  left weight  left distance  right weight  right distance
0          R            1              1             1               2
1          R            1              1             1               3
2          R            1              1             1               4
3          R            1              1             1               5
4          R            1              1             2               1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 624 entries, 0 to 623
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Class Name      624 non-null    object
 1   left weight     624 non-null    int64 
 2   left distance   624 non-null    int64 
 3   right weight    624 non-null    int64 
 4   right distance  624 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 24.5+ KB


In [ ]:
df.describe()

left weight  left distance  right weight  right distance
count   624.000000     624.000000    624.000000      624.000000
mean      3.003205       3.003205      3.003205        3.003205
std       1.414210       1.414210      1.414210        1.414210
min       1.000000       1.000000      1.000000        1.000000
25%       2.000000       2.000000      2.000000        2.000000
50%       3.000000       3.000000      3.000000        3.000000
75%       4.000000       4.000000      4.000000        4.000000
max       5.000000       5.000000      5.000000        5.000000

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
x = df.drop('Class Name',axis = 1)
y = df[['Class Name']]

In [ ]:
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size = 0.3, random_state = 42)

In [ ]:
clf_model = DecisionTreeClassifier(criterion = 'gini',random_state = 42, max_depth = 3, min_samples_leaf=5)
clf_model.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=42)

In [ ]:
y_pred = clf_model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 0  7  5]
 [ 0 60 27]
 [ 0 15 74]]
              precision    recall  f1-score   support

           B       0.00      0.00      0.00        12
           L       0.73      0.69      0.71        87
           R       0.70      0.83      0.76        89

    accuracy                           0.71       188
   macro avg       0.48      0.51      0.49       188
weighted avg       0.67      0.71      0.69       188



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
target = list(df['Class Name'].unique())
feature_names = list(x.columns)

In [ ]:
from sklearn.tree import export_text
r = export_text(clf_model, feature_names=feature_names)
print(r)

|--- left weight <= 2.50
|   |--- right distance <= 2.50
|   |   |--- right weight <= 2.50
|   |   |   |--- class: L
|   |   |--- right weight >  2.50
|   |   |   |--- class: R
|   |--- right distance >  2.50
|   |   |--- right weight <= 1.50
|   |   |   |--- class: R
|   |   |--- right weight >  1.50
|   |   |   |--- class: R
|--- left weight >  2.50
|   |--- left distance <= 2.50
|   |   |--- right weight <= 1.50
|   |   |   |--- class: L
|   |   |--- right weight >  1.50
|   |   |   |--- class: R
|   |--- left distance >  2.50
|   |   |--- right distance <= 3.50
|   |   |   |--- class: L
|   |   |--- right distance >  3.50
|   |   |   |--- class: L

